build: 
	nasm -f elf p6.asm
	ld -m elf_i386 p6.o -o ../../bin/practica6.exe ../../lib/libpc_io.a
run:
	./../../bin/practica6.exe
builda: 
	nasm -f elf p6a.asm
	ld -m elf_i386 p6a.o -o ../../bin/practica6a.exe ../../lib/libpc_io.a
runa:
	./../../bin/practica6a.exe